/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swe;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Chaos
 */
public class Iitem extends javax.swing.JFrame {

    Post getdata = new Post();
    public static Integer postid = -1;
    ArrayList<String> chosen = new ArrayList<>();
    ArrayList<Integer> prob = new ArrayList<>();
    int place = 0;

    /**
     * Creates new form Iitem
     */
    public Iitem(int x) {
        postid = x;
        initComponents();
        getdata = SWE.posts.get(postid);
        questionpane.setVisible(false);
        name.setText(getdata.post_details.getname());
        Category.setText(getdata.post_details.getcategory());
        Date.setText(getdata.post_details.getdate().getDate() + "/" + (getdata.post_details.getdate().getMonth() + 1) + "/"
                + (getdata.post_details.getdate().getYear() + 1900));
        ImageIcon image= new ImageIcon(getdata.post_details.getphoto());
        itempic.setIcon(image);
        idlabel.setText(postid.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name1 = new javax.swing.JLabel();
        answers = new javax.swing.ButtonGroup();
        itempic = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Category = new javax.swing.JLabel();
        Date = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        questionpane = new javax.swing.JPanel();
        ans1 = new javax.swing.JRadioButton();
        item_question = new javax.swing.JLabel();
        ans2 = new javax.swing.JRadioButton();
        ans3 = new javax.swing.JRadioButton();
        submitans = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        idlabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        name1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("YALAHWY.exe");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        itempic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        itempic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250, 153, 0), 3));
        itempic.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        itempic.setMaximumSize(new java.awt.Dimension(299, 210));
        itempic.setPreferredSize(new java.awt.Dimension(299, 210));
        getContentPane().add(itempic, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 170));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(250, 153, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Item Details");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 230, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(250, 153, 0));
        jLabel3.setText("Item Name :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 117, -1));

        name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        name.setForeground(new java.awt.Color(250, 153, 0));
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 270, 17));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(250, 153, 0));
        jLabel4.setText("Item Category :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 120, -1));

        Category.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Category.setForeground(new java.awt.Color(250, 153, 0));
        getContentPane().add(Category, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 270, 17));

        Date.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Date.setForeground(new java.awt.Color(250, 153, 0));
        getContentPane().add(Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 270, 17));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(250, 153, 0));
        jLabel5.setText("Item Found Date :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, -1, -1));

        questionpane.setBackground(new java.awt.Color(51, 51, 51));
        questionpane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        answers.add(ans1);
        ans1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ans1.setForeground(new java.awt.Color(250, 153, 0));
        ans1.setSelected(true);
        ans1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        item_question.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        item_question.setForeground(new java.awt.Color(250, 153, 0));

        answers.add(ans2);
        ans2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ans2.setForeground(new java.awt.Color(250, 153, 0));

        answers.add(ans3);
        ans3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ans3.setForeground(new java.awt.Color(250, 153, 0));

        submitans.setBackground(new java.awt.Color(250, 153, 0));
        submitans.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        submitans.setText("Submin Answer");
        submitans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitansActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout questionpaneLayout = new javax.swing.GroupLayout(questionpane);
        questionpane.setLayout(questionpaneLayout);
        questionpaneLayout.setHorizontalGroup(
            questionpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(questionpaneLayout.createSequentialGroup()
                .addGroup(questionpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(questionpaneLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(item_question, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(questionpaneLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(questionpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ans2)
                            .addComponent(ans1)
                            .addComponent(ans3)))
                    .addGroup(questionpaneLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(submitans)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        questionpaneLayout.setVerticalGroup(
            questionpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, questionpaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(item_question, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ans1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ans2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ans3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(submitans)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        getContentPane().add(questionpane, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, -1, -1));

        jButton1.setBackground(new java.awt.Color(250, 153, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("This Item Is Mine !");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 299, 63));

        jButton2.setBackground(new java.awt.Color(250, 153, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 299, 60));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(250, 153, 0));
        jLabel1.setText("Post ID: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, -1, -1));

        idlabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        idlabel.setForeground(new java.awt.Color(250, 153, 0));
        getContentPane().add(idlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 101, 17));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swe/pics/signupbackground.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        questionpane.setVisible(true);
        item_question.setText(getdata.post_details.detalis.get(0).question);
        Random an = new Random();
        int n = an.nextInt(3);
        prob.add(n);
        ans1.setText(getdata.post_details.detalis.get(0).getans(n));
        ans1.setActionCommand(getdata.post_details.detalis.get(0).getans(n));
        do {
            an = new Random();
            n = an.nextInt(3);
        } while (prob.contains(n));
        prob.add(n);
        ans2.setText(getdata.post_details.detalis.get(0).getans(n));
        ans2.setActionCommand(getdata.post_details.detalis.get(0).getans(n));
        do {
            an = new Random();
            n = an.nextInt(3);
        } while (prob.contains(n));
        prob.add(n);
        ans3.setText(getdata.post_details.detalis.get(0).getans(n));
        ans3.setActionCommand(getdata.post_details.detalis.get(0).getans(n));
        questionpane.revalidate();
        questionpane.repaint();
        place++;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void submitansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitansActionPerformed
        chosen.add(answers.getSelection().getActionCommand());
        prob.clear();
        if (place < getdata.post_details.detalis.size()) {
            item_question.setText(getdata.post_details.detalis.get(place).question);
            Random an = new Random();
            int n = an.nextInt(3);
            prob.add(n);
            ans1.setText(getdata.post_details.detalis.get(place).getans(n));
            ans1.setActionCommand(getdata.post_details.detalis.get(place).getans(n));
            do {
                an = new Random();
                n = an.nextInt(3);
            } while (prob.contains(n));
            prob.add(n);
            ans2.setText(getdata.post_details.detalis.get(place).getans(n));
            ans2.setActionCommand(getdata.post_details.detalis.get(place).getans(n));
            do {
                an = new Random();
                n = an.nextInt(3);
            } while (prob.contains(n));
            prob.add(n);
            ans3.setText(getdata.post_details.detalis.get(place).getans(n));
            ans3.setActionCommand(getdata.post_details.detalis.get(place).getans(n));
            questionpane.revalidate();
            questionpane.repaint();
            place++;
        }
        if (chosen.size() == getdata.post_details.detalis.size()) {
            for (int i = 0; i < chosen.size(); i++) {
                if (!chosen.get(i).equals(getdata.post_details.detalis.get(i).getans(0))) {
                    SWE.logedin.count++;
                    JOptionPane.showMessageDialog(null, "WRONG ANSWERS", "Error", JOptionPane.ERROR_MESSAGE);
                    
                    if (SWE.logedin.count <= 3) {
                        JOptionPane.showMessageDialog(null, "YOU HAVE BEEN BLOCKED", "Error", JOptionPane.ERROR_MESSAGE);
                        SWE.blocked.add(SWE.logedin.getemail());
                        try {
                            SWE.writeblocked();
                        } catch (IOException ex) {
                            Logger.getLogger(Iitem.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        System.exit(0);
                    } else {
                        this.dispose();
                        Isearch next= new Isearch();
                        next.show();
                    }
                    break;
                }
            }
            if (this.isVisible()) {
                for (int i = 0; i < SWE.users.size(); i++) {
                    if (getdata.founder.equals(SWE.users.get(i).getemail())) {
                        String toright = "Finder Name : " + SWE.users.get(i).getname() + "\n" + "Finder Number : " + "0" + SWE.users.get(i).getphone()+"\nAlways Happy To Help You";
                        JOptionPane.showMessageDialog(this, toright, "Finder Data", JOptionPane.PLAIN_MESSAGE);
                        SWE.posts.remove(getdata);
                        
                        try {
                            Post test= new Post();
                            test.setdata();
                            this.dispose();
                            Isearch next = new Isearch();
                            next.show();
                        } catch (IOException ex) {
                            Logger.getLogger(Iitem.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        
                    }
                }
            }
        }
    }//GEN-LAST:event_submitansActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        Isearch next=new Isearch();
        next.show();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Iitem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Iitem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Iitem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Iitem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Iitem(-1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Category;
    private javax.swing.JLabel Date;
    private javax.swing.JRadioButton ans1;
    private javax.swing.JRadioButton ans2;
    private javax.swing.JRadioButton ans3;
    private javax.swing.ButtonGroup answers;
    private javax.swing.JLabel idlabel;
    private javax.swing.JLabel item_question;
    private javax.swing.JLabel itempic;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel name;
    private javax.swing.JLabel name1;
    private javax.swing.JPanel questionpane;
    private javax.swing.JButton submitans;
    // End of variables declaration//GEN-END:variables
}
