/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swe;

import com.toedter.calendar.JTextFieldDateEditor;
import java.awt.Color;
import java.awt.image.ImageFilter;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author karim
 */
public class IPost extends javax.swing.JFrame {

    /**
     * Creates new form IPost
     */
    SWE main=new SWE();
    Post post=new Post();
    File f=null;
    public IPost() {
        initComponents();
        name.setBackground(new Color(0,0,0,80));
        photodic.setBackground(new Color(0,0,0,80));
        finddate.setBackground(new Color(0,0,0,80));
        question.setBackground(new Color(0,0,0,80));
        ans1.setBackground(new Color(0,0,0,80));
        ans2.setBackground(new Color(0,0,0,80));
        ans3.setBackground(new Color(0,0,0,80));
        name_label.setVisible(false);
        pic_label.setVisible(false);
        date_label.setVisible(false);
        question_label.setVisible(false);
        answer1.setVisible(false);
        answer2.setVisible(false);
        answer3.setVisible(false);
        JTextFieldDateEditor editor = (JTextFieldDateEditor) finddate.getDateEditor();
        editor.setEditable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JTextField();
        cat = new javax.swing.JComboBox<>();
        picdic = new javax.swing.JButton();
        photodic = new javax.swing.JTextField();
        finddate = new com.toedter.calendar.JDateChooser();
        submit = new javax.swing.JButton();
        name_label = new javax.swing.JLabel();
        pic_label = new javax.swing.JLabel();
        date_label = new javax.swing.JLabel();
        question = new javax.swing.JTextField();
        ans1 = new javax.swing.JTextField();
        ans2 = new javax.swing.JTextField();
        ans3 = new javax.swing.JTextField();
        question_label = new javax.swing.JLabel();
        answer1 = new javax.swing.JLabel();
        answer3 = new javax.swing.JLabel();
        answer2 = new javax.swing.JLabel();
        submit1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        title_la = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("YALAHWY.exe");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name.setBackground(new java.awt.Color(0, 0, 0));
        name.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        name.setForeground(new java.awt.Color(153, 153, 153));
        name.setText("Enter Name");
        name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameFocusLost(evt);
            }
        });
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 340, 40));

        cat.setBackground(new java.awt.Color(51, 51, 51));
        cat.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        cat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mobiles", "Keys", "Wallets", "Accsesories", "Others" }));
        getContentPane().add(cat, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 340, 40));

        picdic.setBackground(new java.awt.Color(255, 153, 51));
        picdic.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        picdic.setText("browse");
        picdic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                picdicActionPerformed(evt);
            }
        });
        getContentPane().add(picdic, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, -1, 40));

        photodic.setEditable(false);
        photodic.setForeground(new java.awt.Color(255, 153, 0));
        photodic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                photodicActionPerformed(evt);
            }
        });
        getContentPane().add(photodic, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 250, 40));

        finddate.setBackground(new java.awt.Color(51, 51, 51));
        finddate.setDateFormatString("dd/MM/yyyy");
        finddate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        finddate.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                finddateComponentAdded(evt);
            }
        });
        finddate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                finddateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                finddateFocusLost(evt);
            }
        });
        finddate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                finddateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                finddateMouseEntered(evt);
            }
        });
        getContentPane().add(finddate, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 340, 40));

        submit.setBackground(new java.awt.Color(255, 153, 0));
        submit.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        submit.setText("submit");
        submit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        getContentPane().add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 630, 130, 30));

        name_label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        name_label.setForeground(new java.awt.Color(255, 51, 51));
        name_label.setText("please enter a name");
        getContentPane().add(name_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, -1, 40));

        pic_label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pic_label.setForeground(new java.awt.Color(255, 51, 51));
        pic_label.setText("please enter a photo");
        getContentPane().add(pic_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, -1, -1));

        date_label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        date_label.setForeground(new java.awt.Color(255, 51, 51));
        date_label.setText("please pick a date");
        getContentPane().add(date_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, -1, -1));

        question.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        question.setForeground(new java.awt.Color(153, 153, 153));
        question.setText("Enter a Question");
        question.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                questionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                questionFocusLost(evt);
            }
        });
        getContentPane().add(question, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 340, 40));

        ans1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ans1.setForeground(new java.awt.Color(153, 153, 153));
        ans1.setText("Enter The Right Answer");
        ans1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ans1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ans1FocusLost(evt);
            }
        });
        getContentPane().add(ans1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 340, 40));

        ans2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ans2.setForeground(new java.awt.Color(153, 153, 153));
        ans2.setText("Enter a Wrong Answer");
        ans2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ans2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ans2FocusLost(evt);
            }
        });
        getContentPane().add(ans2, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 490, 340, 40));

        ans3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ans3.setForeground(new java.awt.Color(153, 153, 153));
        ans3.setText("Enter a Wrong Answer");
        ans3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ans3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ans3FocusLost(evt);
            }
        });
        getContentPane().add(ans3, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 550, 340, 40));

        question_label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        question_label.setForeground(new java.awt.Color(255, 51, 51));
        question_label.setText("please enter a Question");
        getContentPane().add(question_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 380, -1, -1));

        answer1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        answer1.setForeground(new java.awt.Color(255, 51, 51));
        answer1.setText("please enter an answer");
        getContentPane().add(answer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 440, -1, -1));

        answer3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        answer3.setForeground(new java.awt.Color(255, 51, 51));
        answer3.setText("please enter an answer");
        getContentPane().add(answer3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 560, -1, -1));

        answer2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        answer2.setForeground(new java.awt.Color(255, 51, 51));
        answer2.setText("please enter an answer");
        getContentPane().add(answer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 500, -1, -1));

        submit1.setBackground(new java.awt.Color(255, 153, 0));
        submit1.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        submit1.setText("back");
        submit1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit1ActionPerformed(evt);
            }
        });
        getContentPane().add(submit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 630, 150, 30));

        jButton1.setBackground(new java.awt.Color(255, 153, 0));
        jButton1.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jButton1.setText("Add Question");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 630, 200, 30));

        title_la.setFont(new java.awt.Font("Yu Gothic UI", 1, 50)); // NOI18N
        title_la.setForeground(new java.awt.Color(255, 153, 0));
        title_la.setText("Make a Post ");
        getContentPane().add(title_la, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swe/pics/rsz_1rsz_orangprofile.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 50, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swe/pics/rsz_open-in-browser-icon-11-256.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 50, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swe/pics/rsz_icon_camera.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 50, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swe/pics/rsz_7_calendar_date_year_event_schedule_link_holiday-512.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 50, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swe/pics/rsz_question-circle-orange-2-512.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 50, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swe/pics/rsz__right_icon_1208790.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 50, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swe/pics/rsz_538357-wrong_512x512.png"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 484, 50, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swe/pics/rsz_538357-wrong_512x512.png"))); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 550, 50, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swe/pics/ui-ux-banner.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void picdicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_picdicActionPerformed
        JFileChooser pic=new JFileChooser();
        pic.addChoosableFileFilter(new FileNameExtensionFilter("Image Files", "jpg", "png", "tif"));
        pic.setAcceptAllFileFilterUsed(false);
        if(pic.showOpenDialog(null)==0)
        {
            pic_label.setVisible(false);
            f=pic.getSelectedFile();
            photodic.setText(f.toString());
        }
        else {
            pic_label.setVisible(true);
        }
    }//GEN-LAST:event_picdicActionPerformed

    private void photodicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_photodicActionPerformed
        
    }//GEN-LAST:event_photodicActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        if(finddate.getDate()==null)
            date_label.setVisible(true);
        else
            date_label.setVisible(false);
        if(name_label.isVisible()||picdic.getText().equals("")||date_label.isVisible()||question.getText().equals("Enter a Question")||
                ans1.getText().equals("Enter The Right Answer")||ans2.getText().equals("Enter a Wrong Answer")
                ||ans3.getText().equals("Enter a Wrong Answer")||post.post_details.detalis.size()==0)
        {
            JOptionPane.showMessageDialog(null, "there is somthing wrong", "Error",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            
            post.setid();
            post.post_details.setname(name.getText());
            post.post_details.setdate(finddate.getDate());
            post.post_details.setcategory((String) cat.getSelectedItem());
            post.post_details.setphoto(f.toString());
            post.founder=main.logedin.getemail();
            main.posts.add(post);
            try {
                post.setdata();
            } catch (IOException ex) {
                Logger.getLogger(IPost.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(this, "Post been added Successfully", "Done!",JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_submitActionPerformed

    private void nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFocusLost
        if(name.getText().equals("")){
            name_label.setVisible(true);
            name.setText("Enter Name");
            name.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_nameFocusLost

    private void nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFocusGained
        name_label.setVisible(false);
        if (name.getText().equals("Enter Name")){
            name.setText("");
            name.setForeground(Color.WHITE);
        }
    }//GEN-LAST:event_nameFocusGained

    private void finddateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_finddateFocusGained
       
    }//GEN-LAST:event_finddateFocusGained

    private void finddateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_finddateFocusLost
       
    }//GEN-LAST:event_finddateFocusLost

    private void finddateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_finddateMouseClicked

    }//GEN-LAST:event_finddateMouseClicked

    private void finddateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_finddateMouseEntered
  
    }//GEN-LAST:event_finddateMouseEntered

    private void finddateComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_finddateComponentAdded

    }//GEN-LAST:event_finddateComponentAdded

    private void questionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_questionFocusGained
        question_label.setVisible(false);
        if (question.getText().equals("Enter a Question")){
            question.setText("");
            question.setForeground(Color.WHITE);
        }
    }//GEN-LAST:event_questionFocusGained

    private void questionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_questionFocusLost
        if (question.getText().equals("")){
            question_label.setVisible(true);
            question.setText("Enter a Question");
            question.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_questionFocusLost

    private void ans1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ans1FocusGained
        answer1.setVisible(false);
        if (ans1.getText().equals("Enter The Right Answer")){
            ans1.setText("");
            ans1.setForeground(Color.WHITE);
        }
    }//GEN-LAST:event_ans1FocusGained

    private void ans1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ans1FocusLost
        if (ans1.getText().equals("")){
            answer1.setVisible(true);
            ans1.setText("Enter The Right Answer");
            ans1.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_ans1FocusLost

    private void ans2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ans2FocusGained
        answer2.setVisible(false);
        if (ans2.getText().equals("Enter a Wrong Answer")){
            ans2.setText("");
            ans2.setForeground(Color.WHITE);
        }
    }//GEN-LAST:event_ans2FocusGained

    private void ans2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ans2FocusLost
         if (ans2.getText().equals("")){
            answer2.setVisible(true);
            ans2.setText("Enter a Wrong Answer");
            ans2.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_ans2FocusLost

    private void ans3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ans3FocusGained
       answer3.setVisible(false);
        if (ans3.getText().equals("Enter a Wrong Answer")){
            ans3.setText("");
            ans3.setForeground(Color.WHITE);
        }
    }//GEN-LAST:event_ans3FocusGained

    private void ans3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ans3FocusLost
       if (ans3.getText().equals("")){
            answer3.setVisible(true);
            ans3.setText("Enter a Wrong Answer");
            ans3.setForeground(new Color(153,153,153));
       }
    }//GEN-LAST:event_ans3FocusLost

    private void submit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit1ActionPerformed
        chooserfram next = new chooserfram();
        next.show();
        this.dispose();
    }//GEN-LAST:event_submit1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(question.getText().equals("Enter a Question")||ans1.getText().equals("Enter The Right Answer")||ans2.getText().equals("Enter a Wrong Answer")
                ||ans3.getText().equals("Enter a Wrong Answer"))
        {
            JOptionPane.showMessageDialog(this, "there is somthing wrong", "Error",JOptionPane.ERROR_MESSAGE);
        }
        else{
            Question q=new Question();
            q.question=question.getText();
            String []a=new String[3];
            a[0]=ans1.getText();
            a[1]=ans2.getText();
            a[2]=ans3.getText();
            q.setans(a);
            post.post_details.detalis.add(q);
            question.setText("");
            ans1.setText("");
            ans2.setText("");
            ans3.setText("");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IPost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IPost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IPost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IPost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IPost().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ans1;
    private javax.swing.JTextField ans2;
    private javax.swing.JTextField ans3;
    private javax.swing.JLabel answer1;
    private javax.swing.JLabel answer2;
    private javax.swing.JLabel answer3;
    private javax.swing.JComboBox<String> cat;
    private javax.swing.JLabel date_label;
    private com.toedter.calendar.JDateChooser finddate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField name;
    private javax.swing.JLabel name_label;
    private javax.swing.JTextField photodic;
    private javax.swing.JLabel pic_label;
    private javax.swing.JButton picdic;
    private javax.swing.JTextField question;
    private javax.swing.JLabel question_label;
    private javax.swing.JButton submit;
    private javax.swing.JButton submit1;
    private javax.swing.JLabel title_la;
    // End of variables declaration//GEN-END:variables
}
