/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swe;

import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
/**
 *
 * @author karim
 */
public class ISignup extends javax.swing.JFrame {

    /**
     * Creates new form ISignup
     */SWE main=new SWE();
    public ISignup() {
        initComponents();
        a.setBackground(new Color(0,0,0,80));
        b.setBackground(new Color(0,0,0,80));
        c.setBackground(new Color(0,0,0,80));
        d.setBackground(new Color(0,0,0,80));
        e.setBackground(new Color(0,0,0,80));
        email_label.setVisible(false);
        phone_label.setVisible(false);
        pass_label.setVisible(false); 
        name_label1.setVisible(false);
             
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        submit = new javax.swing.JButton();
        a = new javax.swing.JTextField();
        b = new javax.swing.JTextField();
        e = new javax.swing.JTextField();
        phone_label = new javax.swing.JLabel();
        email_label = new javax.swing.JLabel();
        check = new javax.swing.JCheckBox();
        pass_label = new javax.swing.JLabel();
        d = new javax.swing.JPasswordField();
        c = new javax.swing.JPasswordField();
        name_label1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(810, 650));
        getContentPane().setLayout(null);

        submit.setBackground(new java.awt.Color(0, 0, 0));
        submit.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        submit.setText("Sign Up");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        getContentPane().add(submit);
        submit.setBounds(210, 520, 350, 40);

        a.setText("name");
        a.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                aFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                aFocusLost(evt);
            }
        });
        a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aActionPerformed(evt);
            }
        });
        getContentPane().add(a);
        a.setBounds(210, 140, 340, 40);

        b.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                bFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                bFocusLost(evt);
            }
        });
        b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActionPerformed(evt);
            }
        });
        getContentPane().add(b);
        b.setBounds(210, 210, 340, 40);

        e.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                eFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                eFocusLost(evt);
            }
        });
        e.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eActionPerformed(evt);
            }
        });
        e.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                eKeyTyped(evt);
            }
        });
        getContentPane().add(e);
        e.setBounds(210, 420, 340, 40);

        phone_label.setForeground(new java.awt.Color(255, 51, 51));
        phone_label.setText("wrong number");
        getContentPane().add(phone_label);
        phone_label.setBounds(570, 420, 69, 30);

        email_label.setForeground(new java.awt.Color(255, 51, 51));
        email_label.setText("wrong email");
        getContentPane().add(email_label);
        email_label.setBounds(590, 210, 100, 40);

        check.setFont(new java.awt.Font("Yu Gothic UI", 3, 12)); // NOI18N
        check.setText("show password");
        check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkActionPerformed(evt);
            }
        });
        getContentPane().add(check);
        check.setBounds(580, 280, 130, 40);

        pass_label.setForeground(new java.awt.Color(255, 0, 51));
        pass_label.setText("password does not match");
        getContentPane().add(pass_label);
        pass_label.setBounds(570, 350, 123, 30);

        d.setText("jPasswordField1");
        d.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dFocusLost(evt);
            }
        });
        d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dActionPerformed(evt);
            }
        });
        getContentPane().add(d);
        d.setBounds(210, 350, 340, 40);

        c.setText("jPasswordField2");
        getContentPane().add(c);
        c.setBounds(210, 280, 340, 40);

        name_label1.setFont(new java.awt.Font("Yu Gothic UI", 1, 11)); // NOI18N
        name_label1.setForeground(new java.awt.Color(204, 204, 204));
        name_label1.setText("Name :");
        getContentPane().add(name_label1);
        name_label1.setBounds(210, 120, 110, 20);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 3, 50)); // NOI18N
        jLabel2.setText("Create Account");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(190, 0, 560, 80);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swe/pics/1.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(150, 140, 50, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swe/pics/5.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(150, 210, 50, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swe/pics/3.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(150, 280, 50, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swe/pics/4.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(150, 350, 50, 40);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swe/pics/rsz_2telephone_55698.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(150, 420, 50, 40);

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Password :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(210, 260, 100, 15);

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Confirmation :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(210, 330, 90, 15);

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Email :");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(210, 190, 50, 15);

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Number :");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(210, 400, 70, 15);

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        jLabel12.setText("Please Fill in this Form to Create an Account !");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(250, 80, 450, 16);

        jCheckBox1.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        jCheckBox1.setText("I agree with the Terms & Condations.");
        getContentPane().add(jCheckBox1);
        jCheckBox1.setBounds(210, 470, 290, 25);

        jLabel1.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swe/pics/rsz_background1.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-10, -10, 820, 650);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        if(pass_label.isVisible()||email_label.isVisible()||phone_label.isVisible()||name_label1.isVisible())
        {
            JOptionPane.showMessageDialog(null, "there is somthing wrong", "Error",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            Signup sign=new Signup();
            sign.user.setname(a.getText());
            sign.user.setemail(b.getText());
            sign.user.setpass(c.getText());
            sign.user.setphone(Integer.parseInt(e.getText()));
         
            if(sign.checkvalid(main.users))
            {
                sign.setdata(main.users);
            }
        }
    }//GEN-LAST:event_submitActionPerformed

    private void bFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bFocusLost
       int cnt=0;
        int idxdot=0;
        int idxat=0;
        for(int i=0;i< b.getText().length();i++)
        {
            if(b.getText().charAt(i)=='@')
            {    
                idxat=i;
                cnt++;
            }
            if(b.getText().charAt(i)=='.')
                idxdot=i;
        }
        
        if(cnt!=1||idxat>idxdot)
        {
           email_label.setVisible(true);
        }
        else
            email_label.setVisible(false);
    }//GEN-LAST:event_bFocusLost

    private void bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_bActionPerformed

    private void bFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bFocusGained
        // TODO add your handling code here:
        email_label.setVisible(false);
    }//GEN-LAST:event_bFocusGained

    private void eFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_eFocusLost
        // TODO add your handling code here:
        if(e.getText().length()!=11)
        {
            phone_label.setVisible(true);
        }
    }//GEN-LAST:event_eFocusLost

    private void eFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_eFocusGained
        phone_label.setVisible(false);
    }//GEN-LAST:event_eFocusGained

    private void eKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_eKeyTyped
        char c=evt.getKeyChar();
        if((!(Character.isDigit(c)))||c==KeyEvent.VK_BACK_SPACE||c==KeyEvent.VK_DELETE)
          evt.consume();
    }//GEN-LAST:event_eKeyTyped

    private void checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkActionPerformed
        if (check.isSelected())
        {
            c.setEchoChar((char)0);
            d.setEchoChar((char)0);
        }
        else
        {
            c.setEchoChar('*');
            d.setEchoChar('*');
        }
    }//GEN-LAST:event_checkActionPerformed

    private void dFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dFocusLost
        if(!d.getText().equals(c.getText()))
            pass_label.setVisible(true);
    }//GEN-LAST:event_dFocusLost

    private void dFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dFocusGained
        // TODO add your handling code here:
        pass_label.setVisible(false);
    }//GEN-LAST:event_dFocusGained

    private void aFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_aFocusLost
        if(a.getText().equals(""))
            name_label1.setVisible(true);
    }//GEN-LAST:event_aFocusLost

    private void aFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_aFocusGained
        name_label1.setVisible(false);
    }//GEN-LAST:event_aFocusGained

    private void aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aActionPerformed

    private void eActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eActionPerformed

    private void dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ISignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ISignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ISignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ISignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ISignup().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a;
    private javax.swing.JTextField b;
    private javax.swing.JPasswordField c;
    private javax.swing.JCheckBox check;
    private javax.swing.JPasswordField d;
    private javax.swing.JTextField e;
    private javax.swing.JLabel email_label;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel name_label1;
    private javax.swing.JLabel pass_label;
    private javax.swing.JLabel phone_label;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
