/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swe;

import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
/**
 *
 * @author karim
 */
public class ISignup extends javax.swing.JFrame {

    /**
     * Creates new form ISignup
     */SWE main=new SWE();
    public ISignup() {
        initComponents();
        email_label.setVisible(false);
        phone_label.setVisible(false);
        pass_label.setVisible(false); 
        pass.setEchoChar((char)0);
        pass2.setEchoChar((char)0);
        name_label.setVisible(false);
             
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        submit = new javax.swing.JButton();
        name = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        num = new javax.swing.JTextField();
        phone_label = new javax.swing.JLabel();
        email_label = new javax.swing.JLabel();
        pass_label = new javax.swing.JLabel();
        check = new javax.swing.JCheckBox();
        pass2 = new javax.swing.JPasswordField();
        pass = new javax.swing.JPasswordField();
        name_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        submit.setText("submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        name.setForeground(new java.awt.Color(204, 204, 255));
        name.setText("Name...");
        name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameFocusLost(evt);
            }
        });
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });

        email.setForeground(new java.awt.Color(204, 204, 250));
        email.setText("Example@example.com");
        email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFocusLost(evt);
            }
        });
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });

        num.setForeground(new java.awt.Color(204, 204, 255));
        num.setText("Phone number...");
        num.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                numFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                numFocusLost(evt);
            }
        });
        num.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numKeyTyped(evt);
            }
        });

        phone_label.setForeground(new java.awt.Color(255, 51, 51));
        phone_label.setText("wrong number");

        email_label.setForeground(new java.awt.Color(255, 51, 51));
        email_label.setText("wrong email");

        pass_label.setForeground(new java.awt.Color(255, 0, 51));
        pass_label.setText("password does not match");

        check.setText("show password");
        check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkActionPerformed(evt);
            }
        });

        pass2.setForeground(new java.awt.Color(204, 204, 250));
        pass2.setText("Confirm password...");
        pass2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pass2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pass2FocusLost(evt);
            }
        });
        pass2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass2ActionPerformed(evt);
            }
        });

        pass.setForeground(new java.awt.Color(204, 204, 250));
        pass.setText("Password...");
        pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passFocusLost(evt);
            }
        });
        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });

        name_label.setForeground(new java.awt.Color(255, 51, 51));
        name_label.setText("please enter a name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(pass2)
                        .addComponent(name)
                        .addComponent(pass)
                        .addComponent(email)
                        .addComponent(num)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pass_label)
                    .addComponent(phone_label)
                    .addComponent(check)
                    .addComponent(name_label)
                    .addComponent(email_label))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(check))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addComponent(pass_label, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phone_label))
                .addGap(57, 57, 57)
                .addComponent(submit)
                .addGap(114, 114, 114))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        if(pass_label.isVisible()||email_label.isVisible()||phone_label.isVisible()||name_label.isVisible())
        {
            JOptionPane.showMessageDialog(null, "there is somthing wrong", "Error",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            Signup sign=new Signup();
            sign.user.setname(name.getText());
            sign.user.setemail(email.getText());
            sign.user.setpass(pass.getText());
            sign.user.setphone(Integer.parseInt(num.getText()));
         
            if(sign.checkvalid(main.users))
            {
                sign.setdata(main.users);
            }
        }
    }//GEN-LAST:event_submitActionPerformed

    private void emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusLost
        if(email.getText().equals(""))
        {
            email.setText("Example@example.com");
            email.setForeground(new Color(204,204,250));
        }
        int cnt=0;
        int idxdot=0;
        int idxat=0;
        for(int i=0;i< email.getText().length();i++)
        {
            if(email.getText().charAt(i)=='@')
            {    
                idxat=i;
                cnt++;
            }
            if(email.getText().charAt(i)=='.')
                idxdot=i;
        }
        
        if(cnt!=1||idxat>idxdot)
        {
           email_label.setVisible(true);
        }
        else
            email_label.setVisible(false);
    }//GEN-LAST:event_emailFocusLost

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_emailActionPerformed

    private void emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusGained
        // TODO add your handling code here:
        email_label.setVisible(false);
        if(email.getText().equals("Example@example.com"))
        {
            email.setText("");
            email.setForeground(Color.black);
        }
    }//GEN-LAST:event_emailFocusGained

    private void numFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numFocusLost
        // TODO add your handling code here:
        if(num.getText().length()!=11)
        {
            phone_label.setVisible(true);
        }
        if(num.getText().equals(""))
        {
            num.setText("Phone number...");
            num.setForeground(new Color(204,204,250));
        }
    }//GEN-LAST:event_numFocusLost

    private void numFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numFocusGained
        phone_label.setVisible(false);
        if(num.getText().equals("Phone number..."))
        {
            num.setText("");
            num.setForeground(Color.black);
        }
    }//GEN-LAST:event_numFocusGained

    private void numKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numKeyTyped
        char c=evt.getKeyChar();
        if((!(Character.isDigit(c)))||c==KeyEvent.VK_BACK_SPACE||c==KeyEvent.VK_DELETE)
          evt.consume();
    }//GEN-LAST:event_numKeyTyped

    private void checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkActionPerformed
        if (check.isSelected())
        {
            pass.setEchoChar((char)0);
            pass2.setEchoChar((char)0);
        }
        else
        {
            pass.setEchoChar('*');
            pass2.setEchoChar('*');
        }
    }//GEN-LAST:event_checkActionPerformed

    private void pass2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pass2FocusLost
        if(!pass2.getText().equals(pass.getText()))
            pass_label.setVisible(true);
        if(pass2.getText().equals(""))
        {
            pass2.setEchoChar((char)0);
            pass2.setText("Confirm password...");
            pass2.setForeground(new Color(204,204,255));
        }
    }//GEN-LAST:event_pass2FocusLost

    private void pass2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pass2FocusGained
        // TODO add your handling code here:
        pass_label.setVisible(false);
        if(pass2.getText().equals("Confirm password..."))
        {
            pass2.setEchoChar('*');
            pass2.setText("");
            pass2.setForeground(Color.black);
        }
    }//GEN-LAST:event_pass2FocusGained

    private void nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFocusLost
        if(name.getText().equals(""))
        {
            name.setForeground(new Color(204,204,255));
            name.setText("Name...");
            name_label.setVisible(true);
            
        }
    }//GEN-LAST:event_nameFocusLost

    private void nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFocusGained
        name_label.setVisible(false);
        if(name.getText().equals("Name..."))
        {
            name.setText("");
            name.setForeground(Color.black);
        }
    }//GEN-LAST:event_nameFocusGained

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void passFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passFocusGained
        if(pass.getText().equals("Password..."))
        {
            pass.setEchoChar('*');
            pass.setText("");
            pass.setForeground(Color.black);
        }
    }//GEN-LAST:event_passFocusGained

    private void passFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passFocusLost
        if(pass.getText().equals(""))
        {
            pass.setEchoChar((char)0);
            pass.setText("Password...");
            pass.setForeground(new Color(204,204,255));
        }
    }//GEN-LAST:event_passFocusLost

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passActionPerformed

    private void pass2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pass2ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ISignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ISignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ISignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ISignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ISignup().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox check;
    private javax.swing.JTextField email;
    private javax.swing.JLabel email_label;
    private javax.swing.JTextField name;
    private javax.swing.JLabel name_label;
    private javax.swing.JTextField num;
    private javax.swing.JPasswordField pass;
    private javax.swing.JPasswordField pass2;
    private javax.swing.JLabel pass_label;
    private javax.swing.JLabel phone_label;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
