/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swe;

import java.awt.Color;

/**
 *
 * @author Mohamed Saad
 */
public class mainfram extends javax.swing.JFrame {

    /**
     * Creates new form mainfram
     */
    public mainfram() {
        initComponents();
        x.setBackground(new Color(0,0,0,80));
        y.setBackground(new Color(0,0,0,80));
        z.setBackground(new Color(0,0,0,80));
        //h.setBackground(new Color(0,0,0,10));
        signup.setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        h = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        y = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        z = new javax.swing.JCheckBox();
        x = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        signup = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(810, 530));
        setResizable(false);
        getContentPane().setLayout(null);

        h.setBackground(new java.awt.Color(0, 0, 0));
        h.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        h.setForeground(new java.awt.Color(255, 255, 255));
        h.setText("LOGIN");
        h.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(h);
        h.setBounds(310, 370, 260, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swe/pics/rsz_gui8.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(210, 270, 50, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swe/pics/rsz_gender-male2-512.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(350, 50, 160, 140);

        y.setForeground(new java.awt.Color(204, 204, 204));
        y.setText("Username");
        y.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                yFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                yFocusLost(evt);
            }
        });
        getContentPane().add(y);
        y.setBounds(270, 220, 360, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swe/pics/rsz_1images.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(210, 220, 50, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("forget your password ?");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(540, 320, 140, 20);

        z.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        z.setForeground(new java.awt.Color(255, 255, 255));
        z.setText("Remember Me");
        getContentPane().add(z);
        z.setBounds(210, 320, 120, 23);

        x.setBackground(new java.awt.Color(0, 0, 0));
        x.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        x.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(x);
        x.setBounds(270, 270, 360, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText(" Don't have an account ?");
        jLabel4.setToolTipText("");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(280, 430, 510, 30);

        signup.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        signup.setForeground(new java.awt.Color(255, 255, 255));
        signup.setText("Sign up Now !");
        getContentPane().add(signup);
        signup.setBounds(380, 430, 240, 30);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swe/pics/background1.jpg"))); // NOI18N
        jLabel1.setText("forget your password ?");
        jLabel1.setPreferredSize(new java.awt.Dimension(810, 530));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 810, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void yFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_yFocusGained
        if(y.getText().equals("Username")){
            y.setText("");
            y.setForeground(Color.WHITE);
        }
    }//GEN-LAST:event_yFocusGained

    private void yFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_yFocusLost
        if(y.getText().equals("")){
            y.setText("Username");
            y.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_yFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainfram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainfram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainfram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainfram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainfram().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton h;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton signup;
    private javax.swing.JPasswordField x;
    private javax.swing.JTextField y;
    private javax.swing.JCheckBox z;
    // End of variables declaration//GEN-END:variables
}
