/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swe;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Mohamed Saad
 */
public class mainfram extends javax.swing.JFrame {

    /**
     * Creates new form mainfram
     */
    SWE s=new SWE();
    public mainfram() {
        initComponents();
        password.setBackground(new Color(0,0,0,80));
        name.setBackground(new Color(0,0,0,80));
        signup.setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        h = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        signup = new javax.swing.JButton();
        back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("YALAHWY.exe");
        setPreferredSize(new java.awt.Dimension(810, 530));
        setResizable(false);
        getContentPane().setLayout(null);

        h.setBackground(new java.awt.Color(255, 153, 0));
        h.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        h.setText("LOGIN");
        h.setBorder(new javax.swing.border.MatteBorder(null));
        h.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        h.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hActionPerformed(evt);
            }
        });
        getContentPane().add(h);
        h.setBounds(310, 370, 260, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swe/pics/rsz_orangepass.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(210, 270, 50, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swe/pics/rsz_orangprofile.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(350, 50, 160, 140);

        name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        name.setForeground(new java.awt.Color(204, 204, 204));
        name.setText("Username");
        name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameFocusLost(evt);
            }
        });
        getContentPane().add(name);
        name.setBounds(270, 220, 360, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swe/pics/rsz_1rsz_orangprofile.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(210, 220, 50, 40);

        password.setBackground(new java.awt.Color(0, 0, 0));
        password.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        password.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(password);
        password.setBounds(270, 270, 360, 40);

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 0));
        jLabel4.setText(" Don't have an account ?");
        jLabel4.setToolTipText("");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(310, 430, 180, 30);

        signup.setBackground(new java.awt.Color(255, 153, 51));
        signup.setFont(new java.awt.Font("Yu Gothic UI", 1, 15)); // NOI18N
        signup.setForeground(new java.awt.Color(255, 153, 0));
        signup.setText("Sign up Now !");
        signup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupActionPerformed(evt);
            }
        });
        getContentPane().add(signup);
        signup.setBounds(440, 430, 160, 30);

        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swe/pics/mainframbackground.jpg"))); // NOI18N
        back.setText("forget your password ?");
        back.setPreferredSize(new java.awt.Dimension(810, 530));
        getContentPane().add(back);
        back.setBounds(0, -10, 810, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFocusGained
        if(name.getText().equals("Username")){
            name.setText("");
            name.setForeground(Color.WHITE);
        }
    }//GEN-LAST:event_nameFocusGained

    private void nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFocusLost
        if(name.getText().equals("")){
            name.setText("Username");
            name.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_nameFocusLost

    private void signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupActionPerformed
        ISignup next= new ISignup ();
        next.show();
        this.dispose();
    }//GEN-LAST:event_signupActionPerformed

    private void hActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hActionPerformed
        if(back.getText().equals("Username")||password.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "please enter username and password", "Error",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            Login l = new Login();
            l.email=name.getText();
            l.password=password.getText();
            if(l.checkvalid()){
                    chooserfram next=new chooserfram();
                    next.show();
                    this.dispose();
            }
        }
    }//GEN-LAST:event_hActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainfram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainfram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainfram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainfram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainfram().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JButton h;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField name;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton signup;
    // End of variables declaration//GEN-END:variables
}
