/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swe;

import com.toedter.calendar.JTextFieldDateEditor;
import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;


/**
 *
 * @author Chaos
 */
public class ToModify extends javax.swing.JFrame {
    public static Integer state=-1;
     Post getdata = new Post();
     File f=null;
     int counter=0;
     ArrayList <Question> newquest = new ArrayList<>();
    /**
     * Creates new form ToModify
     */
    public ToModify(int s) {
        
        initComponents();
        name.setBackground(new Color(0,0,0,0));
        photodic.setBackground(new Color(0,0,0,0));
        questionf.setBackground(new Color(0,0,0,20));
        ans1f.setBackground(new Color(0,0,0,20));
        ans2f.setBackground(new Color(0,0,0,20));
        ans3f.setBackground(new Color(0,0,0,20));
        state=s;
        getdata = SWE.posts.get(state);
        name.setText(getdata.post_details.getname());
        cat.setSelectedItem(getdata.post_details.getcategory());
        finddate.setDate(getdata.post_details.getdate());
        photodic.setText(getdata.post_details.getphoto());
        ImageIcon image= new ImageIcon(getdata.post_details.getphoto());
        itempic.setIcon(image);
        JTextFieldDateEditor editor = (JTextFieldDateEditor) finddate.getDateEditor();
        editor.setEditable(false);
        editor.setForeground(new Color(250,153,0));
        editor.setBackground(new Color (0,0,0,0));
        idlabel.setText(state.toString());
        questionf.setText(getdata.post_details.detalis.get(0).question);
        ans1f.setText(getdata.post_details.detalis.get(0).getans(0));
        ans2f.setText(getdata.post_details.detalis.get(0).getans(1));
        ans3f.setText(getdata.post_details.detalis.get(0).getans(2));
        questionpane.revalidate();
        questionpane.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        itempic = new javax.swing.JLabel();
        questionpane = new javax.swing.JPanel();
        submitans = new javax.swing.JButton();
        questionf = new javax.swing.JTextField();
        ans1f = new javax.swing.JTextField();
        ans2f = new javax.swing.JTextField();
        ans3f = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        name = new javax.swing.JTextField();
        cat = new javax.swing.JComboBox<>();
        finddate = new com.toedter.calendar.JDateChooser();
        idlabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        photodic = new javax.swing.JTextField();
        picdic = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("YALAHWY.exe");
        setMaximumSize(new java.awt.Dimension(842, 510));
        setMinimumSize(new java.awt.Dimension(842, 510));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        itempic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        itempic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250, 153, 0), 3));
        itempic.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        itempic.setMaximumSize(new java.awt.Dimension(299, 210));
        itempic.setMinimumSize(new java.awt.Dimension(299, 210));
        itempic.setPreferredSize(new java.awt.Dimension(299, 210));
        getContentPane().add(itempic, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 29, 250, 240));

        questionpane.setBackground(new java.awt.Color(51, 51, 51));
        questionpane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        submitans.setBackground(new java.awt.Color(255, 153, 0));
        submitans.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        submitans.setText("Submin Answer");
        submitans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitansActionPerformed(evt);
            }
        });

        questionf.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        questionf.setForeground(new java.awt.Color(250, 153, 0));
        questionf.setMaximumSize(new java.awt.Dimension(6, 23));

        ans1f.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ans1f.setForeground(new java.awt.Color(250, 153, 0));
        ans1f.setMaximumSize(new java.awt.Dimension(6, 285));
        ans1f.setMinimumSize(new java.awt.Dimension(6, 285));

        ans2f.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ans2f.setForeground(new java.awt.Color(250, 153, 0));

        ans3f.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ans3f.setForeground(new java.awt.Color(250, 153, 0));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 0));
        jLabel6.setText("The Right Answer :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 153, 0));
        jLabel8.setText("The Question :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 153, 0));
        jLabel9.setText("a Wrong Answer :");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 153, 0));
        jLabel10.setText("a Wrong Answer :");

        javax.swing.GroupLayout questionpaneLayout = new javax.swing.GroupLayout(questionpane);
        questionpane.setLayout(questionpaneLayout);
        questionpaneLayout.setHorizontalGroup(
            questionpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, questionpaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submitans)
                .addGap(140, 140, 140))
            .addGroup(questionpaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(questionpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGroup(questionpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(questionpaneLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(questionpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ans2f, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                            .addComponent(ans1f, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(questionf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, questionpaneLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ans3f, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        questionpaneLayout.setVerticalGroup(
            questionpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, questionpaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(questionpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(questionf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(questionpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ans1f, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(questionpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ans2f, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(questionpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ans3f, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submitans)
                .addGap(24, 24, 24))
        );

        getContentPane().add(questionpane, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, -1, 210));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("Item Details");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 98, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("Post ID: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 0));
        jLabel3.setText("Item Name :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 109, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 0));
        jLabel4.setText("Item Category :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 109, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 153, 0));
        jLabel5.setText("Item Found Date :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 153, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setText("Submit Changes");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 308, 250, 71));

        jButton2.setBackground(new java.awt.Color(255, 153, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 412, 250, 41));

        name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        name.setForeground(new java.awt.Color(255, 153, 0));
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 354, 28));

        cat.setBackground(new java.awt.Color(51, 51, 51));
        cat.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        cat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mobiles", "Keys", "Wallets", "Accsesories", "Others" }));
        getContentPane().add(cat, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 350, 30));

        finddate.setBackground(new java.awt.Color(51, 51, 51));
        finddate.setForeground(new java.awt.Color(255, 153, 0));
        finddate.setDateFormatString("dd/MM/yyyy");
        finddate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        finddate.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                finddateComponentAdded(evt);
            }
        });
        finddate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                finddateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                finddateFocusLost(evt);
            }
        });
        finddate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                finddateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                finddateMouseEntered(evt);
            }
        });
        getContentPane().add(finddate, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 350, 30));

        idlabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        idlabel.setForeground(new java.awt.Color(255, 153, 0));
        getContentPane().add(idlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 112, 17));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 153, 0));
        jLabel7.setText("Item Picture :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 113, -1));

        photodic.setEditable(false);
        photodic.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        photodic.setForeground(new java.awt.Color(255, 153, 0));
        photodic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                photodicActionPerformed(evt);
            }
        });
        getContentPane().add(photodic, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 260, 30));

        picdic.setBackground(new java.awt.Color(255, 153, 51));
        picdic.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        picdic.setText("browse");
        picdic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                picdicActionPerformed(evt);
            }
        });
        getContentPane().add(picdic, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 220, 80, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swe/pics/signupbackground.jpg"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitansActionPerformed
        if (questionf.getText().equals("")||ans2f.getText().equals("")||ans1f.getText().equals("")||ans3f.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Enter the Question and all answers ", "Can not submit", JOptionPane.ERROR_MESSAGE);
        }
        else {
            Question x= new Question();
            String []anses= new String [3];
            anses[0]=ans1f.getText();
            anses[1]=ans2f.getText();
            anses[2]=ans3f.getText();
            x.question=questionf.getText();
            x.setans(anses);
            counter++;
            newquest.add(x);
            if (counter <getdata.post_details.detalis.size()){
            questionf.setText(getdata.post_details.detalis.get(counter).question);
            ans1f.setText(getdata.post_details.detalis.get(counter).getans(0));
            ans2f.setText(getdata.post_details.detalis.get(counter).getans(1));
            ans3f.setText(getdata.post_details.detalis.get(counter).getans(2));
        }
            else {
                questionf.setText("");
                ans1f.setText("");
                ans2f.setText("");
                ans3f.setText("");
            }
        }
    }//GEN-LAST:event_submitansActionPerformed

    private void finddateComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_finddateComponentAdded

    }//GEN-LAST:event_finddateComponentAdded

    private void finddateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_finddateFocusGained

    }//GEN-LAST:event_finddateFocusGained

    private void finddateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_finddateFocusLost

    }//GEN-LAST:event_finddateFocusLost

    private void finddateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_finddateMouseClicked

    }//GEN-LAST:event_finddateMouseClicked

    private void finddateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_finddateMouseEntered

    }//GEN-LAST:event_finddateMouseEntered

    private void photodicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_photodicActionPerformed

    }//GEN-LAST:event_photodicActionPerformed

    private void picdicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_picdicActionPerformed
        JFileChooser pic=new JFileChooser();
        pic.addChoosableFileFilter(new FileNameExtensionFilter("Image Files", "jpg", "png", "tif"));
        pic.setAcceptAllFileFilterUsed(false);
        if(pic.showOpenDialog(null)==0)
        {
            f=pic.getSelectedFile();
            photodic.setText(f.toString());
        }
    }//GEN-LAST:event_picdicActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       IModify back = new IModify();
       this.dispose();
       back.show();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (name.getText().equals("")){
            JOptionPane.showMessageDialog(this,"can't leave Empty fields", "Can not submit", JOptionPane.ERROR_MESSAGE);
        }
        else if (newquest.isEmpty()){
            JOptionPane.showMessageDialog(this,"Please Submit Your Questions First", "Can not submit", JOptionPane.ERROR_MESSAGE);
        }
        else {
            SWE.posts.get(state).post_details.setname(name.getText());
            SWE.posts.get(state).post_details.setcategory(cat.getSelectedItem().toString());
            SWE.posts.get(state).post_details.setdate(finddate.getDate());
            SWE.posts.get(state).post_details.setphoto(photodic.getText());
            SWE.posts.get(state).post_details.detalis.clear();
            for (int i=0;i<newquest.size();i++)
                SWE.posts.get(state).post_details.detalis.add(newquest.get(i));
            try {
                JOptionPane.showMessageDialog(this,"Post Modified Successfully", "Done !", JOptionPane.PLAIN_MESSAGE);
                getdata.setdata();
                IModify next = new IModify ();
                next.show();
                this.dispose();
            } catch (IOException ex) {
                Logger.getLogger(ToModify.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ToModify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ToModify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ToModify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ToModify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ToModify(state).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ans1f;
    private javax.swing.JTextField ans2f;
    private javax.swing.JTextField ans3f;
    private javax.swing.JComboBox<String> cat;
    private com.toedter.calendar.JDateChooser finddate;
    private javax.swing.JLabel idlabel;
    private javax.swing.JLabel itempic;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField name;
    private javax.swing.JTextField photodic;
    private javax.swing.JButton picdic;
    private javax.swing.JTextField questionf;
    private javax.swing.JPanel questionpane;
    private javax.swing.JButton submitans;
    // End of variables declaration//GEN-END:variables
}
